public enum TwitterOAuthScope: String {
    case blockRead = "block.read"
    case blockWrite = "block.write"
    case bookmarkRead = "bookmark.read"
    case bookmarkWrite = "bookmark.write"
    case followRead = "follow.read"
    case followWrite = "follow.write"
    case likeRead = "like.read"
    case likeWrite = "like.write"
    case listRead = "list.read"
    case listWrite = "list.write"
    case muteRead = "mute.read"
    case muteWrite = "mute.write"
    case offlineAccess = "offline.access"
    case spaceRead = "space.read"
    case tweetModerateWrite = "tweet.moderate.write"
    case tweetRead = "tweet.read"
    case tweetWrite = "tweet.write"
    case usersRead = "users.read"
}
